version: "3"

services:
  appsmith:
    build: ./
    env_file: 
      - fat-container.env
    ports:
      - "18081:80"
      - "18080:8080"
  mongo:
    image: mongo:4.4.6
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_DATABASE=appsmith
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=gu123451
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro

  redis:
    image: redis
    expose:
      - "6379"
    